version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tictactoe-server
    environment:
      # Supabase Database URLs - replace [YOUR-PASSWORD] with actual password
      DATABASE_URL: postgresql://postgres.mtiphcbwkyuykalnzavc:[YOUR-PASSWORD]@aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true
      DIRECT_URL: postgresql://postgres.mtiphcbwkyuykalnzavc:[YOUR-PASSWORD]@aws-1-ap-south-1.pooler.supabase.com:5432/postgres
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRATION: 7d
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  client:
    build:
      context: ./clients
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
    container_name: tictactoe-client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped

# No volumes needed for Supabase (cloud database)
